package tutorials

import (
	"fyne.io/fyne"
)

// Tutorial defines the data structure for a tutorial
type Tutorial struct {
	Title, Intro string
	View         func(w fyne.Window) fyne.CanvasObject
}

var (
	// Tutorials defines the metadata for each tutorial
	Tutorials = map[string]Tutorial{
		"welcome": {"Welcome",
			"Welcome to the Fyne toolkit tutorials.\nChoose an area from the options on the left.",
			welcomeScreen,
		},
		"canvas": {"Canvas",
			"See the canvas capabilities.",
			canvasScreen,
		},
		"icons": {"Theme Icons",
			"Browse the embedded icons.",
			iconScreen,
		},
		"containers": {"Containers",
			"Containers and collections.",
			containerScreen,
		},
		"apptabs": {"AppTabs Container",
			"A container to help divide up an application into functional areas.",
			makeAppTabsTab,
		},
		"border": {"Border Container",
			"A container that positions items around a central content.",
			makeBorderLayout,
		},
		"box": {"Box Container",
			"A container arranges items in horizontal or vertical list.",
			makeBoxLayout,
		},
		"center": {"Center Container",
			"A container to that centers child elements.",
			makeCenterLayout,
		},
		"grid": {"Grid Container",
			"A container that arranges all items in a grid.",
			makeGridLayout,
		},
		"split": {"Split Container",
			"A split container divides the container in two pieces that the user can resize.",
			makeSplitTab,
		},
		"scroll": {"Scroll Container",
			"A container that provides scrolling for it's content.",
			makeScrollTab,
		},
		"widgets": {"Widgets",
			"Browse the toolkit widgets.",
			widgetScreen,
		},
		"accordion": {"Accordion",
			"Expand or collapse content panels.",
			makeAccordionTab,
		},
		"button": {"Button",
			"Simple widget for user tap handling.",
			makeButtonTab,
		},
		"card": {"Card",
			"Group content and widgets.",
			makeCardTab,
		},
		"form": {"Form",
			"Gathering input widgets for data submiission.",
			makeFormTab,
		},
		"input": {"Input",
			"A collection of widgets for user input.",
			makeInputTab,
		},
		"text": {"Text",
			"Text handling widgets.",
			makeTextTab,
		},
		"toolbar": {"Toolbar",
			"A row of shortcut icons for common tasks.",
			makeToolbarTab,
		},
		"progress": {"Progress",
			"Show duration or the need to wait for a task.",
			makeProgressTab,
		},
		"collections": {"Collection Widgets",
			"Learn about the collection widgets.",
			collectionScreen,
		},
		"list": {"List Collection",
			"A vertical arrangement of cached elements with the same styling.",
			makeListTab,
		},
		"table": {"Table Collection",
			"A two dimensional cached collection of cells.",
			makeTableTab,
		},
		"tree": {"Tree Collection",
			"A tree based arrangement of cached elements with the same styling.",
			makeTreeTab,
		},
		"dialogs": {"Dialogs",
			"Work with dialogs.",
			dialogScreen,
		},
		"windows": {"Windows",
			"Window function demo.",
			windowScreen,
		},
		"advanced": {"Advanced",
			"Debug and advanced information.",
			advancedScreen,
		},
	}

	// TutorialIndex  defines how our tutorials should be laid out in the index tree
	TutorialIndex = map[string][]string{
		"":            {"welcome", "canvas", "icons", "widgets", "collections", "containers", "dialogs", "windows", "advanced"},
		"collections": {"list", "table", "tree"},
		"containers":  {"apptabs", "border", "box", "center", "grid", "split", "scroll"},
		"widgets":     {"accordion", "button", "card", "form", "input", "text", "toolbar", "progress"},
	}
)
