version: "2"

linters:
  enable:
    - errcheck
    - gocyclo
    - gosec
    - govet
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: cmd/fyne/ # The whole tool is deprecated
        linters:
          - errcheck
          - gosec
          - revive
          - staticcheck
      - path: cmd/fyne_demo/ # The whole tool is deprecated
        linters:
          - errcheck
          - gosec
          - revive
      - path: test/ # In tests, the usage of deprecated stuff is valid to check for compatibility.
        linters:
          - staticcheck
        text: "SA1019"
      - path: _test\.go # TODO: Clarify whether we should explicitly handle errors in tests (e.g., using require.NoError()).
        linters:
          - errcheck
  settings:
    gosec:
      excludes:
        - G104 # gosec does not have a sophisticated ignore for unchecked errors; we rely on errcheck, instead
        # 3**: gosec is quite pedantic about permissions … even the standard library does not fulfil the tests
        - G301
        - G302
        - G304
        - G306
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
          - allowFloats: "0.0,0.25,0.5,0.75,1.0"
            allowInts: "0,1,2,3,4,5,100,0xff,0xffff"
            allowStrs: '""'
            ignoreFuncs: "strconv\\.Format.*,strconv\\.Parse.*"
          exclude:
            - "**/*_test.go"
            - "**/test/**"
        - name: argument-limit
          disabled: true # TODO
        - name: blank-imports
          disabled: true # TODO
        - name: bool-literal-in-expr
          disabled: true # TODO
        - name: cognitive-complexity
          disabled: true
        - name: comment-spacings
          disabled: true # TODO
        - name: confusing-naming
          disabled: true # TODO
        - name: confusing-results
          disabled: true # TODO
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true # TODO
        - name: early-return
          disabled: true # TODO
        - name: empty-block
          disabled: true # TODO
        - name: empty-lines
          disabled: true # TODO
        - name: enforce-switch-style
          disabled: true # TODO
        - name: epoch-naming
          disabled: true # TODO
        - name: exported
          disabled: true # TODO
        - name: filename-format
          disabled: true # TODO
        - name: flag-parameter
          disabled: true # TODO
        - name: function-length
          disabled: true # TODO
        - name: function-result-limit
          disabled: true # TODO
        - name: get-return
          disabled: true # TODO
        - name: identical-ifelseif-branches
          disabled: true # TODO
        - name: identical-switch-branches
          disabled: true # TODO
        - name: import-alias-naming
          disabled: true # TODO
        - name: import-shadowing
          disabled: true # TODO
        - name: increment-decrement
          disabled: true # TODO
        - name: indent-error-flow
          disabled: true # TODO
        - name: inefficient-map-lookup
          disabled: true # TODO
        - name: line-length-limit
          disabled: true # TODO
        - name: max-public-structs
          disabled: true # TODO
        - name: nested-structs
          disabled: true # TODO
        - name: package-comments
          disabled: true # TODO
        - name: package-naming
          disabled: true # TODO
        - name: redefines-builtin-id
          disabled: true # TODO
        - name: redundant-test-main-exit
          disabled: true # TODO
        - name: struct-tag
          disabled: true # TODO
        - name: unchecked-type-assertion
          disabled: true # TODO
        - name: unexported-naming
          disabled: true # TODO
        - name: unexported-return
          disabled: true # TODO
        - name: unhandled-error
          disabled: true # we rely on errcheck
        - name: unnecessary-format
          disabled: true # TODO
        - name: unnecessary-stmt
          disabled: true # TODO
        - name: unused-parameter
          disabled: true # TODO
        - name: unused-receiver
          disabled: true # TODO
        - name: use-slices-sort
          disabled: true # TODO
        - name: var-declaration
          disabled: true # TODO
    staticcheck:
      checks:
        - all
        - -ST1000
