// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import "fyne.io/fyne/v2"

var resourceAuthors = &fyne.StaticResource{
	StaticName: "AUTHORS",
	StaticContent: []byte(
		"Andy Williams <andy@andy.xyz>\nSteve OConnor <steveoc64@gmail.com>\nLuca Corbo <lu.corbo@gmail.com>\nPaul Hovey <paul@paulhovey.org>\nCharles Corbett <nafredy@gmail.com>\nTilo Prütz <tilo@pruetz.net>\nStephen Houston <smhouston88@gmail.com>\nStorm Hess <stormhess@gloryskulls.com>\nStuart Scott <stuart.murray.scott@gmail.com>\nJacob Alzén <jacalz@tutanota.com>\nCharles A. Daniels <charles@cdaniels.net>\nPablo Fuentes <f.pablo1@hotmail.com>\nChangkun Ou <hi@changkun.de>\nCedric Bail\nDrew Weymouth\n\n"),
}
