// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package lang

import "fyne.io/fyne/v2"

var resourceBaseFrJson = &fyne.StaticResource{
	StaticName: "base.fr.json",
	StaticContent: []byte(
		"{\n  \"Quit\": \"Quitter\"\n}\n"),
}
var resourceBaseTemplateJson = &fyne.StaticResource{
	StaticName: "base.template.json",
	StaticContent: []byte(
		"{\n  \"Quit\": \"Quit\"\n}\n"),
}
